# Seleccion y filtrado de datos parte 1 - Distintas "Metodos() y Atributos"

In [89]:
import pandas as pd

df_vic = pd.read_csv(
    '../Bases_datos/agresiones_general.csv'
)
#print(df_vic.head())
#print(df_vic.info())
df_vic=df_vic.set_index('Index')
#df_vic.loc[2]

"""varios indices"""

#df_vic.loc[[2,3,4,5]]

"""varios indices y solo algunas columnas (Filtro de columnas)"""

#df_vic.loc[[2,3,4,5],['Area_unit_2013_label','Victimisations_calendar_year_2015','Urban_area_type']]

"""Filtro de columna"""

#df_vic['Urban_area_type'].unique()

"""filtro de filas que se repiten bajo cierta categoria"""

#df_vic.loc[df_vic['Urban_area_type']=='Main urban area']

'filtro de filas que se repiten bajo cierta categoria'

| Símbolo             | Uso principal en Pandas                              | Ejemplos correctos                                                                                                                        | Qué hace                                                |
| ------------------- | ---------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------- |
| **`()`** paréntesis | Ejecutar un **método** de un DataFrame o Serie       | `df.head(5)`<br>`df.describe()`<br>`df.groupby("col").sum()`                                                                              | Llama a la función/método y devuelve un resultado       |
| **`[]`** corchetes  | **Seleccionar datos** (columnas, filas, condiciones) | `df["col"]` → una columna (Serie)<br>`df[["col1","col2"]]` → varias columnas (DataFrame)<br>`df[df["col"] > 10]` → filtrado por condición | Extrae datos por etiqueta o posición                    |
| **`{}`** llaves     | Diccionarios para mapeo o creación de DataFrames     | `pd.DataFrame({"A":[1,2], "B":[3,4]})`<br>`df.replace({"A": {"old": "new"}})`                                                             | Estructuras clave-valor usadas en reemplazos o creación |

In [90]:
"""METODO INDEX: indicar a python que la comuna indice es la columna indice"""

#df_vic=df_vic.set_index('index') #dice index porque el nombre de la columna realmente se llama indix pero podria ser cualquier nombre

'METODO INDEX: indicar a python que la comuna indice es la columna indice'

In [91]:
"""METODO HEAD: filtrar por numero de columnas, Ej: quiero ver las 10 primeras"""

df_vic.head(10)

,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
Index,,,,,,,,,,,,,
1,514102,Auckland Central West,550,15900,346,6.6,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
2,573101,Willis Street-Cambridge Terrace,447,8300,539,10.3,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
3,529700,Hamilton Central,380,3170,"1,199",22.9,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region
4,514103,Auckland Central East,375,13250,283,5.4,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
5,591500,Cathedral Square,305,570,"5,351",102.3,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region
6,514101,Auckland Harbourside,253,5680,445,8.5,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
7,524604,Manukau Central,192,900,"2,133",40.8,5,Southern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
8,562800,Palmerston North Central,190,3060,621,11.9,16,Palmerston North,Main urban area,40,Palmerston North City,8,Manawatu-Wanganui Region
9,540410,Kuirau,168,1290,"1,302",24.9,10,Rotorua,Main urban area,24,Rotorua District,4,Bay of Plenty Region
10,538201,Tauranga Central,167,2270,736,14.1,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region

In [92]:
"""METODO INFO: muestra los nombres de las columnas"""

df_vic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2020 entries, 1 to 2020
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Area_unit_2013_code                    2020 non-null   int64
 1   Area_unit_2013_label                   2020 non-null   object
 2   Victimisations_calendar_year_2015      2020 non-null   int64
 3   Population_mid_point_2015              2020 non-null   int64
 4    Rate_per_10000_population             2020 non-null   object
 5    Rate_ratio_NZ_average_rate            2020 non-null   object
 6   Urban_area_2013_code                   2020 non-null   int64
 7   Urban_area_2013_label                  2020 non-null   object
 8   Urban_area_type                        2020 non-null   object
 9   Territorial_authority_area_2013_code   2020 non-null   int64
 10  Territorial_authority_area_2013_label  2020 non-null   object
 11  Region_2013_code                       2020 non-null   int64
 12  Region_2013_label                      2020 non-null   object
dtypes: int64(6), object(7)
memory usage: 220.9+ KB

In [93]:
"""INDEXADOR LOC () - atributo especial accessor: localizar y filtra los indices indicados (va entre corchetes porque no es una funcion,
es un idexador) (tambien es necesario escribir la funcion set_index porque python por default comienza por 0 y por lo general las listas
comienzan en 1)"""

df_vic.loc[2]

Area_unit_2013_code                                               573101
Area_unit_2013_label                     Willis Street-Cambridge Terrace
Victimisations_calendar_year_2015                                    447
Population_mid_point_2015                                           8300
 Rate_per_10000_population                                           539
 Rate_ratio_NZ_average_rate                                         10.3
Urban_area_2013_code                                                  20
Urban_area_2013_label                                    Wellington Zone
Urban_area_type                                          Main urban area
Territorial_authority_area_2013_code                                  47
Territorial_authority_area_2013_label                    Wellington City
Region_2013_code                                                       9
Region_2013_label                                      Wellington Region
Name: 2, dtype: object

In [94]:
"""INDEXADOR LOC: encontrar varios indices a la vez (usa doble corchete ya que le vas a pasar una lsita)"""

df_vic.loc[[2,3,4,5]]

,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
Index,,,,,,,,,,,,,
2,573101,Willis Street-Cambridge Terrace,447,8300,539,10.3,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
3,529700,Hamilton Central,380,3170,"1,199",22.9,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region
4,514103,Auckland Central East,375,13250,283,5.4,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
5,591500,Cathedral Square,305,570,"5,351",102.3,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region

In [95]:
"""FUNCION UNIQUE: filtra solo una columna (va en corchetes porque los corchetes tienen la funcion de seleccionar datos)"""

df_vic['Urban_area_type'].unique()

array(['Main urban area', 'Secondary urban area', 'Minor urban area',
       'Rural area'], dtype=object)

In [96]:
"""FUNCION LOC + datos de columna (filtrar los datos dentro de una columna) esto es como indice y coincidir en excel"""

df_vic.loc[df_vic['Urban_area_type']=='Main urban area']

#Obtendrás todas las filas donde Urban_area_type es 'Main urban area'.
#es como aplicar filtros sobre una columna en excel

,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
Index,,,,,,,,,,,,,
1,514102,Auckland Central West,550,15900,346,6.6,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
2,573101,Willis Street-Cambridge Terrace,447,8300,539,10.3,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
3,529700,Hamilton Central,380,3170,"1,199",22.9,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region
4,514103,Auckland Central East,375,13250,283,5.4,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
5,591500,Cathedral Square,305,570,"5,351",102.3,22,Christchurch,Main urban area,60,Christchurch City,13,Canterbury Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,573514,Churton Park South,0,3440,-,-,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
2017,610601,Grasmere,0,3590,-,-,24,Invercargill,Main urban area,75,Invercargill City,15,Southland Region
2018,536513,Bethlehem East,0,3590,-,-,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region
2019,574302,Te Kainga,0,4020,-,-,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
2020,527007,Horsham Downs,0,5440,-,-,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region

In [97]:
"""ATRIBUTO COLUMNS: devuelve el nombre de las columnas"""

df_vic.columns

Index(['Area_unit_2013_code', 'Area_unit_2013_label',
       'Victimisations_calendar_year_2015', 'Population_mid_point_2015',
       ' Rate_per_10000_population ', ' Rate_ratio_NZ_average_rate ',
       'Urban_area_2013_code', 'Urban_area_2013_label', 'Urban_area_type',
       'Territorial_authority_area_2013_code',
       'Territorial_authority_area_2013_label', 'Region_2013_code',
       'Region_2013_label'],
      dtype='object')

In [98]:
"""FILTRO POR COLUMNAS (solo las 10 primeras)"""

df_vic[['Area_unit_2013_code','Area_unit_2013_label']].head()

       Area_unit_2013_code             Area_unit_2013_label
Index
1                   514102            Auckland Central West
2                   573101  Willis Street-Cambridge Terrace
3                   529700                 Hamilton Central
4                   514103            Auckland Central East
5                   591500                 Cathedral Square

In [99]:
"""METODO ISNA (NaN - que faltan registros o vacios)"""

df_vic.isna()

,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
Index,,,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,False,False,False,False,False,False,False,False,False,False,False,False,False
2017,False,False,False,False,False,False,False,False,False,False,False,False,False
2018,False,False,False,False,False,False,False,False,False,False,False,False,False
2019,False,False,False,False,False,False,False,False,False,False,False,False,False
2020,False,False,False,False,False,False,False,False,False,False,False,False,False

In [100]:
"""METODO ISNA + FILTRO DE COLUMNA"""

df_vic[df_vic['Area_unit_2013_code'].isna()]

#el resultado indica que no hay nunguna columa en nan o null

Empty DataFrame
Columns: [Area_unit_2013_code, Area_unit_2013_label, Victimisations_calendar_year_2015, Population_mid_point_2015,  Rate_per_10000_population ,  Rate_ratio_NZ_average_rate , Urban_area_2013_code, Urban_area_2013_label, Urban_area_type, Territorial_authority_area_2013_code, Territorial_authority_area_2013_label, Region_2013_code, Region_2013_label]
Index: []

In [101]:
"""METODO ISIN: filtra los valores de una colmna
1.- nombre de la columna
2.- nombre de la nueva lista que quieres filtrar"""

newdf=['Auckland Central West', 'Hamilton Central']

df_vic[df_vic['Area_unit_2013_label'].isin(newdf)]

#se crea una lista nueva para no tener que escribir los nombres de nuevo

,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
Index,,,,,,,,,,,,,
1,514102,Auckland Central West,550,15900,346,6.6,4,Central Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
3,529700,Hamilton Central,380,3170,"1,199",22.9,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region

## signos para unir varias condiciones logicas al mismo tiempo

- & (and) Se cumplen ambas condiciones
- | (or) Se cumple al menos una condicion
- ~ (not) Negacion

In [102]:
df_vic[(df_vic['Urban_area_type']=='Secondary urban area') & (df_vic['Victimisations_calendar_year_2015']<253)]

,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
Index,,,,,,,,,,,,,
17,609302,Queenstown Hill,113,4100,276,5.3,117,Queenstown,Secondary urban area,70,Queenstown-Lakes District,14,Otago Region
28,525910,Pukekohe North,91,9980,91,1.7,101,Pukekohe,Secondary urban area,76,Auckland,2,Auckland Region
29,609304,Queenstown Bay,90,2360,381,7.3,117,Queenstown,Secondary urban area,70,Queenstown-Lakes District,14,Otago Region
30,541720,Taupo Central,90,3900,231,4.4,103,Taupo,Secondary urban area,21,Taupo District,3,Waikato Region
40,599500,Seaview,78,2540,307,5.9,113,Timaru,Secondary urban area,64,Timaru District,13,Canterbury Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1927,597714,Fairton,0,730,-,-,112,Ashburton,Secondary urban area,63,Ashburton District,13,Canterbury Region
1934,554113,Tawhiti,0,820,-,-,105,Hawera,Secondary urban area,35,South Taranaki District,7,Taranaki Region
1952,584800,Karoro,0,970,-,-,111,Greymouth,Secondary urban area,56,Grey District,12,West Coast Region
1983,541319,Lakewood,0,1540,-,-,103,Taupo,Secondary urban area,21,Taupo District,3,Waikato Region
2000,586122,Lehmans,0,2200,-,-,116,Rangiora,Secondary urban area,59,Waimakariri District,13,Canterbury Region

In [103]:
df_vic[(df_vic['Urban_area_type']=='Secondary urban area') | (df_vic['Victimisations_calendar_year_2015']<253)]

,Area_unit_2013_code,Area_unit_2013_label,Victimisations_calendar_year_2015,Population_mid_point_2015,Rate_per_10000_population,Rate_ratio_NZ_average_rate,Urban_area_2013_code,Urban_area_2013_label,Urban_area_type,Territorial_authority_area_2013_code,Territorial_authority_area_2013_label,Region_2013_code,Region_2013_label
Index,,,,,,,,,,,,,
7,524604,Manukau Central,192,900,"2,133",40.8,5,Southern Auckland Zone,Main urban area,76,Auckland,2,Auckland Region
8,562800,Palmerston North Central,190,3060,621,11.9,16,Palmerston North,Main urban area,40,Palmerston North City,8,Manawatu-Wanganui Region
9,540410,Kuirau,168,1290,"1,302",24.9,10,Rotorua,Main urban area,24,Rotorua District,4,Bay of Plenty Region
10,538201,Tauranga Central,167,2270,736,14.1,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region
11,603100,Stuart St-Frederick St,154,3360,458,8.8,23,Dunedin,Main urban area,71,Dunedin City,14,Otago Region
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,506653,Riverhead,0,3510,-,-,502,Rural (Incl.some Off Shore Islands),Rural area,76,Auckland,2,Auckland Region
2017,610601,Grasmere,0,3590,-,-,24,Invercargill,Main urban area,75,Invercargill City,15,Southland Region
2018,536513,Bethlehem East,0,3590,-,-,9,Tauranga,Main urban area,23,Tauranga City,4,Bay of Plenty Region
2019,574302,Te Kainga,0,4020,-,-,20,Wellington Zone,Main urban area,47,Wellington City,9,Wellington Region
2020,527007,Horsham Downs,0,5440,-,-,6,Hamilton Zone,Main urban area,16,Hamilton City,3,Waikato Region

In [104]:
df_vic[(df_vic['Urban_area_type']=='Secondary urban area') ~ (df_vic['Victimisations_calendar_year_2015']<253)]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3789235669.py, line 1)

## exportando otra base de datos para desarrollar mas filtos

In [118]:
df_at=pd.read_csv(
    '../Bases_datos/Accidentes_tránsito_carretera-Sutran.csv',encoding='latin1',sep=';'
) # si nos fijamos tránsito lleva tilde en la "a" y seguramente muchos caracteres de la tabla tambien
df_at

,FECHA_CORTE,FECHA,HORA,DEPARTAMENTO,CODIGO_VÍA,KILOMETRO,MODALIDAD,FALLECIDOS,HERIDOS
0,20211222,20200101,05:40,LIMA,PE-1S,24,DESPISTE,0,0
1,20211222,20200101,16:30,CAJAMARCA,PE-3N,74,DESPISTE,0,0
2,20211222,20200101,07:45,PASCO,PE-3N,103,DESPISTE,0,1
3,20211222,20200101,18:30,CAJAMARCA,PE-08,111,DESPISTE,0,2
4,20211222,20200101,18:40,LIMA,PE-1N,174,DESPISTE,0,5
...,...,...,...,...,...,...,...,...,...
8150,20211222,20210930,01:30,ANCASH,PE-1N,348,CHOQUE,0,0
8151,20211222,20210930,04:00,MADRE DE DIOS,PE-30C,417,CHOQUE,0,0
8152,20211222,20210930,15:10,LA LIBERTAD,PE-1N,627,CHOQUE,0,2
8153,20211222,20210930,02:50,LAMBAYEQUE,PE-1N,758,DESPISTE,0,0
8154,20211222,20210930,18:47,PUNO,PE-3S,1296,CHOQUE,1,0

PORQUE SE USA ENCODING: porque sale el siguiente eror: Ese UnicodeDecodeError te está diciendo básicamente:

"Pandas intentó leer el CSV asumiendo que está en UTF-8, pero encontró caracteres que no cuadran con esa 
codificación".

Esto es muy común cuando trabajas con archivos CSV que vienen de Excel, gobiernos o sistemas antiguos, porque 
suelen estar en Latin-1 (ISO-8859-1) o Windows-1252 en lugar de UTF-8.

Si el archivo tiene acentos, tildes, ñ, u otros caracteres especiales guardados con otra codificación, Python 
se confunde y lanza UnicodeDecodeError.

Usar latin1 o ISO-8859-1 le dice a Pandas cómo interpretar esos bytes.

y el SEP= es para convertir ";" en comas ya que el formato csv generalmente esta separado por comas, y si 
en el archivo esta separado por ; (dependiendo de la version de excel) entonces hay que convertir

In [ ]:
""""""